[i18n][man] add missing deunicode().
We get the following error message when we have a translated admonition
(e.g. 'note') label:

  Exception occurred:
      File "../sphinx/sphinx/locale/__init__.py", line 75, in __str__
        return str(self.data)
        UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)